debian_roles:
  - bash
  - fzf
  - nvim
  - nvm
  - tmux
  - zips

arch_roles:
  - awesome
  - bash
  - discord
  - ephoto
  - firefox
  - fonts
  - fzf
  - kitty
  - nitrogen
  - nvim
  - nvm
  - pavucontrol
  # - pulseaudio
  - rofi
  - shotgun
  - spotify
  - tmux
  - yay
  - zips
