- name: "Yay | Create Downloads Directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Downloads/"
    state: directory
    mode: '0755'

- name: "Yay | Install base-devel"
  become: true
  become_user: root
  community.general.pacman:
    name: base-devel
    state: present

- name: "Yay | Gather package facts"
  ansible.builtin.package_facts:
    manager: pacman

- name: "Yay | Clone yay-bin repository"
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ ansible_user_dir }}/Downloads/yay-bin"
  when: ("yay" not in ansible_facts.packages)

- name: "Yay | makepkg"
  ansible.builtin.shell: "cd '{{ ansible_user_dir }}/Downloads/yay-bin' && makepkg -si --noconfirm"
  when: ("yay" not in ansible_facts.packages)
