- name: "Bash | Link debian .bash_profile"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/debian/files/debian/.bash_profile"
    dest: "{{ ansible_user_dir }}/.bash_profile"
    state: link
