- name: "Bash | Delete debian .bash_profile if it exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.bash_profile"
    state: absent

- name: "Bash | Link debian .bash_profile"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/bash/files/debian/.bash_profile"
    dest: "{{ ansible_user_dir }}/.bash_profile"
    state: link
