- name: "Bash | link .bashrc"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/bash/files/.bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    state: link

- name: "Bash | Link bash to .config"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/bash/files/bash"
    dest: "{{ ansible_user_dir }}/.config/bash"
    state: link

- name: "Bash | Run Debian Tasks"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Bash | Run Arch Tasks"
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

