---
- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"

- name: "Bash | Copy .bash_aliases"
  ansible.builtin.copy:
    src: ".bash_aliases"
    dest: "{{ ansible_user_dir }}/.bash_aliases"
    mode: "0644"

- name: "Bash | Copy .bash_logout"
  ansible.builtin.copy:
    src: ".bash_logout"
    dest: "{{ ansible_user_dir }}/.bash_logout"
    mode: "0644"

- name: "Bash | Copy .bash_profile"
  ansible.builtin.copy:
    src: ".bash_profile"
    dest: "{{ ansible_user_dir }}/.bash_profile"
    mode: "0644"

- name: "Bash | Copy .tmuxster.bash"
  ansible.builtin.copy:
    src: ".tmuxster.bash"
    dest: "{{ ansible_user_dir }}/.tmuxster.bash"
    mode: "0644"

