---
- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"

- name: "Bash | Copy .bash_aliases"
  ansible.builtin.copy:
    src: ".bash_aliases"
    dest: "{{ ansible_user_dir }}/.bash_aliases"
    mode: "0644"

- name: "Bash | Copy .bash_logout"
  ansible.builtin.copy:
    src: ".bash_logout"
    dest: "{{ ansible_user_dir }}/.bash_logout"
    mode: "0644"

- name: "Bash | Copy .tmuxster.bash"
  ansible.builtin.copy:
    src: ".tmuxster.bash"
    dest: "{{ ansible_user_dir }}/.tmuxster.bash"
    mode: "0644"

- name: "Bash | Run Ubuntu Tasks"
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: "Bash | Run Arch Tasks"
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
