- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"

- name: "Bash | Copy bash to .config"
  ansible.builtin.copy:
    src: "bash"
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Bash | Run Ubuntu Tasks"
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: "Bash | Run Arch Tasks"
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
