- name: "Postman | Gather package facts"
  ansible.builtin.package_facts:
    manager: pacman

- name: "Postman | Install postman on Arch"
  ansible.builtin.shell: >
    yay -S postman-bin --noconfirm
  when: ("yay-bin" in ansible_facts.packages) and ("postman-bin" not in ansible_facts.packages)

