- name: "NVM | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/nvm-sh/nvm/releases/latest
  register: nvm_latest_version_json
  changed_when: false

- name: "NVM | Registering NVM Latest Release"
  ansible.builtin.set_fact:
    nvm_latest_release: "{{ nvm_latest_version_json.json.tag_name }}"

- name: "NVM | Registering NVM Latest Version"
  ansible.builtin.set_fact:
    nvm_latest_version: "{{ nvm_latest_release.stdout | default('') }}"

- name: "NVM | Show nvm_latest_release debug"
  ansible.builtin.debug:
    var: nvm_latest_release

- name: "NVM | Clone latest version"
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ ansible_env.HOME }}/.nvm"
    version: "{{ nvm_latest_release }}"

- name: "NVM | Install latest node"
  ansible.builtin.shell: >
    source ~/.nvm/nvm.sh && nvm install node
  args:
    executable: /bin/bash

- name: "NVM | Use latest node"
  ansible.builtin.shell: >
    source ~/.nvm/nvm.sh && nvm use node
  args:
    executable: /bin/bash

- name: "NVM | Install latest npm"
  ansible.builtin.shell: >
    source ~/.nvm/nvm.sh && nvm install-latest-npm
  args:
    executable: /bin/bash

