- name: "PulseAudio | Gather package facts"
  ansible.builtin.package_facts:
    manager: pacman

- name: "PulseAudio | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: pulseaudio
    state: present
  # pipewire-pulse conflicts with pulseaudio and will throw errors
  when: ("pipewire-pulse" not in ansible_facts.packages)
