- name: "Picom | Check if yay already installed"
  ansible.builtin.shell: "command -v yay"
  register: result
  ignore_errors: true

- name: "picom | Install picom-arian8j2-git"
  ansible.builtin.shell: "yay -S picom-arian8j2-git --noconfirm"
  when: result.rc == 0

- name: "picom | Configure picom"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/picom/files/picom"
    dest: "{{ ansible_user_dir }}/.config/picom"
    state: link

