- name: "Picom | Check if yay already installed"
  ansible.builtin.shell: "command -v yay"
  register: result
  ignore_errors: true

- name: "picom | Install picom-arian8j2-git"
  ansible.builtin.shell: "yay -S picom-arian8j2-git --noconfirm"
  when: result.rc == 0

- name: "picom | Configure picom"
  ansible.builtin.copy:
    src: picom
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

