- name: "Kitty | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: kitty
    state: present

- name: "Kitty | Configure kitty"
  ansible.builtin.copy:
    src: kitty
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
