- name: "Kitty | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: kitty
    state: present

- name: "Kitty | Configure kitty"
  ansible.builtin.file:
    src: "{{ playbook_dir}}/roles/kitty/files/kitty"
    dest: "{{ ansible_user_dir }}/.config/kitty"
    state: link
