- name: "fzf | Uninstall APT fzf"
  become: true
  become_user: root
  ansible.builtin.apt:
    name: fzf
    state: absent

- name: "fzf | Clone Latest Version"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ ansible_user_dir }}/.fzf"
  register: result

- name: "Install fzf"
  ansible.builtin.shell: "{{ ansible_user_dir }}/.fzf/install --all --no-update-rc --no-zsh --no-fish"
  args:
    executable: /bin/bash
  when: result.rc == 0

