- name: "fzf | Run Debian tasks"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "fzf | Run Arch tasks"
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

- name: "fzf | Install fzf-git"
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf-git.sh.git
    depth: 1
    dest: "{{ ansible_env.HOME }}/.fzf-git"

