- name: "Rofi | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: rofi
    state: present

- name: "Rofi | Configure rofi"
  ansible.builtin.copy:
    src: rofi
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
