- name: "Tmux | Run Debian tasks"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Tmux | Run Arch tasks"
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

- name: "Tmux | Delete tmux if it exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: absent

- name: "Tmux | Configure tmux"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/tmux/files/tmux"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    state: link
