- name: "PavuControl | Install on Arch"
  community.general.pacman:
    name: pavucontrol
    state: present
  become_user: root

- name: "PavuControl | Configure pavucontrol"
  ansible.builtin.copy:
    src: pavucontrol.ini
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

