- name: "PavuControl | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: pavucontrol
    state: present

- name: "PavuControl | Delete pavucontrol.ini if it exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/pavucontrol.ini"
    state: absent

- name: "PavuControl | Configure pavucontrol"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/pavucontrol/files/pavucontrol.ini"
    dest: "{{ ansible_user_dir }}/.config/pavucontrol.ini"
    state: link

