- name: "Awesome | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: awesome
    state: present

- name: "Awesome | Gather package facts"
  ansible.builtin.package_facts:
    manager: pacman

- name: "Awesome | Install lain widgets"
  ansible.builtin.shell: "yay -S lain-git --noconfirm"
  when: ("yay" in ansible_facts.packages) and ("lain-git" not in ansible_facts.packages)

- name: "Awesome | Delete awesome if it exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/awesome"
    state: absent

- name: "Awesome | Configure awesome"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/awesome/files/awesome-config/awesome"
    dest: "{{ ansible_user_dir }}/.config/awesome"
    state: link
