- name: "Awesome | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: awesome
    state: present

- name: "Awesome | Configure awesome"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/roles/awesome/files/awesome"
    dest: "{{ ansible_user_dir }}/.config/awesome"
    state: link
