- name: "Neovim | Install dependencies on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name:
      - cmake
      - curl
      - wget
      - unzip
      - ripgrep
      - gcc
      - python
      - java
    state: present

- name: "Neovim | Install on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: neovim
    state: present
