- name: "Neovim | Install dependencies on Debian"
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - wget
      - unzip
      - ripgrep
      - gcc
      - python3
      - python-is-python3
      - python3-venv
      - default-jdk
      - software-properties-common
    state: present

- name: "Neovim | Add unstable ppa on Debian"
  become: true
  become_user: root
  ansible.builtin.shell: >
    sudo add-apt-repository ppa:neovim-ppa/unstable -y

- name: "Neovim | Install on Debian"
  become: true
  become_user: root
  ansible.builtin.apt:
    name: neovim
    state: present
    update-cache: true

