- name: "Neovim | Install dependencies on Debian"
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - wget
      - unzip
      - ripgrep
      - gcc
      - python
      - java
      - software-properties-common
    state: present

- name: "Neovim | Add unstable ppa on Debian"
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present

- name: "Neovim | Install on Debian"
  become: true
  become_user: root
  ansible.builtin.apt:
    name: neovim
    state: present
    update-cache: true

