- name: "Neovim | Run Debian tasks"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Neovim | Run Arch tasks"
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

- name: "Neovim | Configure nvim"
  ansible.builtin.copy:
    src: nvim
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

