- name: "Bat | How to install on Debian"
  ansible.builtin.debug:
    msg: "Because apt sucks, you must install this manually, as the version on apt right now is incompatible with delta. Go to the releases page, download the deb file, and run `dpkg -i file.deb`. https://github.com/sharkdp/bat/releases"

