- name: "Bat | Run Debian tasks"
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Bat | Run Arch tasks"
  ansible.builtin.import_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

