- name: "Fonts | Install ttf-agave-nerd on Arch"
  become_user: root
  become: true
  community.general.pacman:
    name: ttf-agave-nerd
    state: present

- name: "Fonts | Install noto-fonts on Arch"
  become_user: root
  become: true
  community.general.pacman:
    name: noto-fonts
    state: present
