- name: "Fonts | Install ttf-agave-nerd on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: ttf-agave-nerd
    state: present

- name: "Fonts | Install noto-fonts on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: noto-fonts
    state: present

- name: "Fonts | Install noto-fonts-cjk on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: noto-fonts-cjk
    state: present

- name: "Fonts | Install inter-font on Arch"
  become: true
  become_user: root
  community.general.pacman:
    name: inter-font
    state: present

